name: Kino Bot 24/7

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install python-telegram-bot==21.5 nest_asyncio python-dotenv
      - name: Botni ishga tushirish
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python kinonew.py
